#!/bin/bash
set -e
VERSION=$(ruby -r ./version.rb -e 'puts $VERSION')

cat > Sources/Core/Classes/SdkVersion.swift <<EOF
// Generated by set_version.sh from version.rb — do not edit manually.
enum SdkVersion {
    static let current = "$VERSION"
}
EOF
