#!/bin/bash
set -e
VERSION=$(ruby -r ./version.rb -e 'puts $VERSION')
/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $VERSION" Sources/Core/Info.plist

# Regenerate the version the SDK reports to the API. It cannot be read from the bundle:
# when the SDK is linked statically — the default for both SwiftPM and CocoaPods — the
# classes end up in the host app, so Bundle(for:) resolves to the application, not the SDK.
cat > Sources/Core/Classes/SdkVersion.swift <<EOF
/// Generated by set_version.sh from version.rb — do not edit manually.
public enum SdkVersion {
    /// The version of the SDK, as published. Worth logging alongside anything you report to ReachFive.
    public static let current = "$VERSION"
}
EOF
