= application(_:continue:restorationHandler:)

[.signature]
[subs="normal"]
----
AppDelegate.reachfive().application(<<application, application>>, continue: <<applicationUserActivity, userActivity>>, restorationHandler: <<applicationRestorationHandler, restorationHandler>>)
----

== Description

Allows {company} to handle user activity continuation such as handoffs, and more importantly, universal links.

This method is required by xref:index.adoc#wechat-connect[WeChat] and by providers whose login finishes on a universal link.

Call this method in response to the equivalent UIKit method link:https://developer.apple.com/documentation/uikit/uiapplicationdelegate/[`application(_:continue:restorationHandler:)`^]. If your app uses scenes, forward link:https://developer.apple.com/documentation/uikit/uiscenedelegate/[`scene(_:continue:)`^] here as well.

[IMPORTANT]
====
The method returns a `Bool` that tells you whether {company} actually consumed the activity. Do not assume {company} handles every universal link you forward. When `false` is returned, your app should route the link itself.

Universal-link delivery requires an `applinks:<host>` Associated Domain (see xref:index.adoc#configure-the-ios-sdk[Configure the SDK]).
====

== Examples

[source, swift]
----
include::example${docname}.swift[]
----

== Parameters

[cols="3,7a"]
|===
|Parameter |Description

include::partial$params.adoc[tag="application"]
include::partial$params.adoc[tag="applicationUserActivity"]
include::partial$params.adoc[tag="applicationRestorationHandler"]

|===
