:mobile-sdk:
= Getting Started

{sdk-ios-version-badge}

[.expand]
icon:warning[] Breaking changes for `10.0.0`, please read.

[.expand-content]
====
[discrete]
include::partial$announcements/1000-breaking-changes.adoc[leveloffset=+1]
====

== Requirements

The minimal iOS version of an application using the {company} iOS SDKs has to be `{min-ios-version}`.

include::docs::partial$domain-url-client-id-prereq.adoc[]

== iOS specific prerequisites

* The xref:docs:ROOT:clients.adoc[client] must be a `First-party client` with `Token Endpoint Authentication Method` set to `None`.
* You must have the schemes registered in `Allowed Callback URLs`.
* You should enforce PKCE for security purposes and enable Refresh Tokens for convenience.

icon:book[] For more on configuring a client, see xref:docs:ROOT:clients.adoc#configure-client-first[Set up a client].

== Installation

{company} SDKs are available with Swift Package Manager as independent modules.
Only <<wechat-connect,WeChat Connect>> still uses Cocoapods.

NOTE: If you are migrating from CocoaPods, `import Reach5` no longer brings `UIKit` or `Foundation` into scope.
Add an explicit `import UIKit` and `import Foundation` in each file that uses those types.

TIP: You can also find releases directly on the {company} repo at link:https://github.com/ReachFive/reachfive-ios/releases/[ReachFive iOS SDK^].

Below, you'll find a description and instructions for installation for each module.

* <<SDK Core>>
* <<Facebook native provider>>
* <<Google native provider>>
* <<WeChat Connect>>

---

=== SDK Core

The core SDK contains all the main tools, interfaces, and methods related to standard authentication by identifier and password, passkey, passwordless, and so on.

==== Installation

Add the package dependency with XCode using this package URL:

[source]
----
https://github.com/ReachFive/reachfive-ios.git
----

Or directly add this to the dependencies in `Package.swift`

[source,swift,subs="attributes"]
----
dependencies: [
    .package(url: "https://github.com/ReachFive/reachfive-ios.git", .upToNextMajor(from: "{sdk-ios-latest-version}"))
]
----

==== Configuration

Configure your application's `Info.plist` file with the following XML snippet:

[source,xml]
----
<!-- Info.plist -->

<key>CFBundleURLTypes</key>
<array>
    <dict>
        <key>CFBundleTypeRole</key>
        <string>Editor</string>
        <key>CFBundleURLSchemes</key>
        <array>
            <string>reachfive-${clientId}</string>
        </array>
    </dict>
</array>
----

TIP: See <<Info.plist reference>> for a comprehensive look at the file.

[#facebook-native-provider]
=== Facebook native provider

This module uses the Facebook native SDK to provide a better user experience.

TIP: Refer to the xref:docs::facebook.adoc[] guide to create your Facebook application.

==== Installation

Add the package dependency with XCode using this package URL:

[source]
----
https://github.com/ReachFive/reachfive-ios-facebook.git
----

Or directly add this to the dependencies in `Package.swift`

[source,swift,subs="attributes"]
----
dependencies: [
    .package(url: "https://github.com/ReachFive/reachfive-ios-facebook.git", .upToNextMajor(from: "{sdk-ios-facebook-latest-version}"))
]
----

==== Configuration

NOTE: If you're using the latest version of the Facebook API, remove the `user_gender` scope from the {company} client configuration to prevent any issues.

. Configure the `Info.plist` file with the following XML snippet that contains data about your application:
+
[source, xml]
----
<!-- Info.plist -->

<key>CFBundleURLTypes</key>
<array>
    <dict>
        <key>CFBundleURLSchemes</key>
        <array>
            <string>fb$(YOUR_FACEBOOK_APPLICATION_ID)</string>
        </array>
    </dict>
</array>
<key>FacebookAppID</key>
<string>$(YOUR_FACEBOOK_APPLICATION_ID)</string>
<key>FacebookClientToken</key>
<string>$(YOUR_FACEBOOK_CLIENT_TOKEN)</string>
<key>FacebookDisplayName</key>
<string>$(YOUR_APPLICATION_NAME)</string>
----

. Then to use any of the Facebook dialogs (e.g., Login, Share, App Invites, etc.) that can perform an app switch to Facebook apps, include the following lines:
+
[source, xml]
----
<!-- Info.plist -->

<key>LSApplicationQueriesSchemes</key>
<array>
    <string>fbauth2</string> <1>
    <string>fbapi</string>
    <string>fb-messenger-share-api</string>
</array>
----
<1> Required for <<Fast App Switch>>, which `Reach5Facebook` supports from 9.0.0.

TIP: See <<Info.plist reference>> for a comprehensive look at the file.

==== Fast App Switch

Fast App Switch sends the user to the native Facebook app to sign in instead of to a Safari view controller, so a user already signed in to the Facebook app does not have to sign in again.
The `fbauth2` scheme lets the SDK open the Facebook app, and `fbapi` lets it detect that the app is installed.

The `appSwitch` parameter is `.enabled` by default.
Pass `appSwitch: .disabled` to xref:providerCreator.adoc#FacebookProvider[`FacebookProvider`] to always use the browser flow.

Your login still completes through the browser flow in these cases:

* The Facebook app is not installed, in which case the Facebook SDK falls back on its own.
* Meta has not enabled Fast App Switch for your Facebook application, as the feature is controlled remotely, and classic and limited logins are gated separately.

[NOTE]
====
You get a classic login only when you build the provider with `prefersLoginTracking: .enabled`, the default being `.limited`, and App Tracking Transparency is authorized on the device.
Otherwise the SDK asks Facebook for a limited login.

An app switch returns to your application through the `fb$(YOUR_FACEBOOK_APPLICATION_ID)` scheme you declared above.
Forward xref:application/applicationOpenUrl.adoc[`+application(_:open:options)+`] to {company}, and `+scene(_:openURLContexts:)+` too if your application uses scenes, otherwise the login never completes after the user approves in the Facebook app.
====

=== Google native provider

This module uses the Google native SDK to provide a better user experience.

TIP: Refer to the xref:docs:ROOT:google.adoc[] guide to create your Google application.

==== Installation

Add the package dependency with XCode using this package URL:

[source]
----
https://github.com/ReachFive/reachfive-ios-google.git
----

Or directly add this to the dependencies in `Package.swift`

[source,swift,subs="attributes"]
----
dependencies: [
    .package(url: "https://github.com/ReachFive/reachfive-ios-google.git", .upToNextMajor(from: "{sdk-ios-google-latest-version}"))
]
----

==== Configuration

Configure the `Info.plist` file with the following XML snippet that contains data about your application:

. Add your Google Client ID to the `Info.plist` file:
+
[source,xml]
----
<!-- Info.plist -->

<key>GIDClientID</key>
<string>GOOGLE_CLIENT_ID</string> <1>
----
<1> This is your Google Client ID in standard format. For example, `1234567890-abcdefg.apps.googleusercontent.com`.
+
See <<Info.plist reference>> for a comprehensive look at the file.

. Add your reversed Google Client ID to the URL Scheme.
+
[source,xml,subs=verbatim]
----
<key>CFBundleURLTypes</key>
<array>
<dict>
    <key>CFBundleTypeRole</key>
    <string>Editor</string>
    <key>CFBundleURLSchemes</key>
    <array>
        <string>YOUR_REVERSED_GOOGLE_CLIENT_ID</string> <1>
    </array>
</dict>
</array>
----
<1> The URL Scheme is the reversed Google Client ID (not {company}'s xref:docs:ROOT:clients.adoc[clientID]), which is your Google Client ID with the order of the dot-delimited fields reversed.
For example, `com.googleusercontent.apps.abcdefg-1234567890`.
+
See <<Info.plist reference>> for a comprehensive look at the file.

[#wechat-connect]
=== WeChat Connect

As of {localdate}, WeChat is not yet available for our iOS SDK version {sdk-ios-latest-version}.
We will update this page accordingly when it is available.

This module uses the WeChat native SDK to be able to interact with the WeChat app.

==== Installation

[tabs]
====
Cocoapods::
+
--

. Add this line to your `Podfile` file.
+
[source,subs="normal,callouts"]
----
pod 'IdentitySdkWeChat', '~> {sdk-ios-wechat-latest-version}' <1>
----
<1> `{sdk-ios-wechat-latest-version}` is the latest version of SDK.

. Then run:
+
[source, javascript]
----
pod install
----

--
Swift Package Manager::
+
--
Swift Package Manager is not yet supported.
--

====

==== Configuration

- Configure the `Info.plist` file with the following XML snippet that contains data about your application:
+
[source,xml]
----
<!-- Info.plist -->

<key>LSApplicationQueriesSchemes</key>
<array>
    <string>weixin</string>
    <string>weixinULAPI</string>
    <string>weixinURLParamsAPI</string>
</array>
----

TIP: See <<Info.plist reference>> for a comprehensive look at the file.

// initialize the ios sdk
include::partial$r_configure.adoc[leveloffset=+1]

include::partial$r_initialize.adoc[leveloffset=+1]

== iOS methods

The sidebar contains are all the functions/methods accessible via the iOS SDK.

In all the code examples, the {company} client is instantiated and stored in your `AppDelegate` class.
You can access it through the `AppDelegate.reachfive()` method as shown here and in <<Configuration>>.

[source,swift]
----
    // Return the ReachFive client
    static func reachfive() -> ReachFive {
        let app = UIApplication.shared.delegate as! AppDelegate
        return app.reachfive
    }
----

== Info.plist reference

If you configure all four SDKs, your `Info.plist` file should contain the following ``XML`` Snippet.

// IMPORTANT: This snippet represents what is needed for the latest iOS SDK version which is currently ``{sdk-ios-latest-version}``.

[source,xml]
----
<key>CFBundleURLTypes</key>
<array>
   <dict>
      <key>CFBundleURLSchemes</key>
      <array>
         <string>fb1634029666893228</string>
      </array>
   </dict>
   <dict>
      <key>CFBundleTypeRole</key>
      <string>Editor</string>
      <key>CFBundleURLSchemes</key>
      <array>
         <string>com.googleusercontent.apps.abcdefg-1234567890</string>
      </array>
   </dict>
   <dict>
      <key>CFBundleTypeRole</key>
      <string>Editor</string>
      <key>CFBundleURLSchemes</key>
      <array>
         <string>reachfive-TYAIHFRJ2a1FGJ1T8pKD</string>
      </array>
   </dict>
</array>
<key>GIDClientID</key>
<string>1234567890-abcdefg.apps.googleusercontent.com</string>
<key>FacebookAppID</key>
<string>1634029666893228</string>
<key>FacebookClientToken</key>
<string>ec97b21afcd93ce699091a774a90e2e5</string>
<key>FacebookDisplayName</key>
<string>Reach5 SDK Mobile</string>
<key>GIDClientID</key>
<string>abcdefg-1234567890.apps.googleusercontent.com</string>
<key>LSApplicationQueriesSchemes</key>
<array>
   <string>weixin</string>
   <string>weixinULAPI</string>
   <string>weixinURLParamsAPI</string>
   <string>fbauth2</string>
   <string>fbapi</string>
   <string>fb-messenger-share-api</string>
</array>
----
