/// Generated by set_version.sh from version.rb — do not edit manually.
public enum SdkVersion {
    /// The version of the SDK, as published. Worth logging alongside anything you report to ReachFive.
    public static let current = "11.1.0"
}
