// tag::GoogleProvider[]
|[[GoogleProvider,GoogleProvider]]GoogleProvider
|The object for configuring xref:index.adoc#google-native-provider[Google native provider] for our iOS SDK.

Optionally takes a variant parameter.

[source,swift]
----
GoogleProvider(variant: "native") <1>
----

<1> available starting `Reach5Google` 7.1.0

// end::GoogleProvider[]

// tag::FacebookProvider[]
|[[FacebookProvider,FacebookProvider]]FacebookProvider
|The object for configuring xref:docs:ROOT:facebook-native-provider[Facebook native provider] for our iOS SDK.

Optionally takes two parameters:

- variant `string`: the provider variant to use
- prefersLoginTracking `FBSDKLoginKit.LoginTracking`: Indicates to the Facebook SDK preference for limited or classic login. Facebook SDK is ultimately responsible for the decision.

[source,swift]
----
FacebookProvider(
    variant: "ios", <1>
    prefersLoginTracking: .limited <2>
)
----
<1> available starting `Reach5Facebook` 7.1.0
<2> available starting `Reach5Facebook` 7.2.0

// end::FacebookProvider[]

// tag::AppleProvider[]
|[[AppleProvider,AppleProvider]]AppleProvider|

Optionally takes a variant parameter.
Not specifying `AppleProvider` at all in the providerCreators array is equivalent specifying `AppleProvider` with no variant.

[source,swift]
----
AppleProvider(variant: "native") <1>
----
<1> available starting `Reach5` 7.1.3

// end::AppleProvider[]

// tag::WeChat[]
|[[WeChat,WeChat]]WeChat
|The object for configuring xref:docs:ROOT:wechat-connect[WeChat Connect] for our iOS SDK.

No parameter

[source,swift]
----
WeChat()
----

// end::WeChat[]
